owner: betutubR
repo: br-betutu-status

sites:
  - name: BR Betutu Bot Dashboard
    url: https://br-betutu-bot.onrender.com/dashboard

status-website:
  baseUrl: /br-betutu-status
  name: BR Betutu Bot Status
